version: '3.8'

services:
  backend:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: go run .
    networks:
      - go-webapp-network

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=Chat-App
    volumes:
      - db:/data/db
    networks:
      - go-webapp-network

  frontend:
    depends_on:
      - backend
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    networks:
      - go-webapp-network

volumes:
  db:

networks:
  go-webapp-network:
    driver: bridge
