package message

const (
	FailedToReadBody              = "Failed to read the body."
	FailedToHashPassword          = "Failed to hash the password."
	EmailInUse                    = "User with this email already exist."
	EmailInvalid                  = "Invalid Email."
	SlugInUse                     = "Channel with this name alreday exist."
	FailedToInsert                = "Failed to insert the data."
	EmailValid                    = "Email field should be a valid email address."
	EmailOrPasswordNotMatched     = "Email or password are not matched."
	UserDataCantBeExtracted       = "Unable to extract the userdata."
	SomethingWrong                = "Something Went Wrong. Please try again."
	RequestIsNotAuthorised        = "Your request is not authorized."
	UserNameNotValid              = "Username should contain only alphanumeric character."
	UsernameIsAvailable           = "Username is available."
	UsernameIsNotAvailable        = "Username is not available."
	FailedToCreateRoom            = "Failed to create room."
	FailedToGetRoom               = "Failed to get room."
	FailedToGetChannel            = "Failed to get channel."
	FailedToGetUsers              = "Failed to get users."
	MediaSizeError                = "Media size is should be less then 5MB."
	UserNotExist                  = "User not exists."
	UnauthorizedUser              = "Unauthorized user."
	FileFetchingError             = "Error while fetching the file."
	GeneralInvalidFile            = "Please provide video file as per the specification : Allowed size: 100MB & Allowed type:[.mkv, .mp4, .flv, .pdf, .png, .jpg, .jpeg]."
	InvalidSizeOrType             = "Invalid file type or size."
	FailedToUpdateLastOpenedBy    = "Failed to update the last opened by user."
	AuthorizationRequestInvalid   = "Request is not authorized."
	AuthorizationTokenNotSupplied = "Authorization token was not supplied."
	AuthorizationTokenInvalid     = "Invalid authorization token."
	FailedToGetMessages           = "Failed to get messages."
	MultipleAdminMessage          = "You are the only admin in this group. You can't leave the group."
)
